
version: '3'

services:
  uploader:
    build: .
    environment:
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - PHOTOS_DIR=/photos
    volumes:
      - /Users/edomsha/Desktop/photos/Takeout/Google Photos:/photos
