
version: '3'

services:
  uploader:
    build: .
    environment:
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - PHOTOS_DIR=/photos
      - PARALLEL_UPLOADS=${PARALLEL_UPLOADS}
    volumes:
      - ${PHOTOS_MNT}:/photos
