name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        # Username used to log against the Docker registry
        username: "${{ secrets.DOCKER_USERNAME }}"
        # Password or personal access token used to log against the Docker registry
        password: "${{ secrets.DOCKER_PASSWORD }}"
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag edomsha/media2nextcloud:latest-linux
    - name: push docker image
      run: docker push edomsha/media2nextcloud:latest-linux
