name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag edomsha/googlephotos2nextcloud:latest
    - name: docker push
      run: docker push edomsha/googlephotos2nextcloud:latest
